version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-src
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend-src
    ports:
      - "80:80"

networks:
  main-network:
    driver: bridge
